eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: eureka-host1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-host1
  client:
    serviceUrl:
      defaultZone: http://eureka-host2:8762/eureka/

---
spring:
  profiles: eureka-host2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-host2
  client:
    serviceUrl:
      defaultZone: http://eureka-host1:8761/eureka/